[workspace]
resolver = "3"
members = ["nailkov"]

[workspace.dependencies]
log = { version = "0.4.27", features = ["std"] }
serde = { version = "1.0.219", features = ["derive"] }
rand_core = "0.9.3"
rand = { version = "0.9", default-features = false }
rand_distr = { version = "0.5.1" }
wyrand = { version = "0.3.2", features = ["wyhash", "fully_randomised_wyhash"] }
hashbrown = { version = "0.15.2", default-features = false, features = [
    "equivalent",
    "inline-more"
] }
unicode-segmentation = "1.12.0"
itertools = "0.14.0"
parking_lot = "0.12.3"
indexmap = "2.9.0"

[package]
name = "nailpit"
version = "0.1.0"
edition = "2024"

[features]
tracing = ["fastrace/enable"]

[dependencies]
nailkov = { path = "nailkov" }
axum = { version = "0.8.1", default-features = false, features = [
    "tokio",
    "http1",
    "http2",
] }
axum-core = { version = "0.5.0", default-features = false }
hyper = { version = "1.6.0", default-features = false, features = ["server"] }
hyper-util = { version = "0.1.10", default-features = false, features = [
    "server",
    "server-auto",
] }
tokio = { version = "1.43.0", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "time",
    "parking_lot",
    "net",
    "signal",
] }
tokio-stream = { version = "0.1.17" }
tower-service = { version = "0.3.3", default-features = false }
color-eyre = { version = "0.6.3", default-features = false }
wyrand = { workspace = true, features = ["threadrng_wyhash"] }
getrandom = { version = "0.3.2", features = ["std"] }
rand_core.workspace = true
rand.workspace = true
log.workspace = true
fastrace = { version = "0.7.9" }
fastrace-axum = "0.1.0"
logforth = { version = "0.23.1", features = ["fastrace"] }
tower = { version = "0.5.2", features = ["buffer", "limit"] }
futures-concurrency = "7.6.3"
bytes = "1.10.1"
futures-lite = "2.6.0"
scc = "2.3.3"
parking_lot = { workspace = true, features = ["arc_lock"] }

[profile.release]
codegen-units = 1
lto = "fat"
strip = true
panic = "abort"
