[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
authors = ["Gonçalo Rica Pais da Silva <bluefinger@gmail.com>"]
edition = "2024"
repository = "https://github.com/Bluefinger/nailpit"
version = "0.1.0"
license = "AGPL-3.0-only"
rust-version = "1.89.0"

[workspace.lints.clippy]
undocumented_unsafe_blocks = "warn"

[workspace.dependencies]
axum = { version = "0.8.1", default-features = false, features = [
    "tokio",
    "http1",
    "http2",
    "macros",
] }
axum-core = { version = "0.5.0", default-features = false }
bytes = "1.10.1"
hyper = { version = "1.6.0", default-features = false, features = ["server"] }
color-eyre = { version = "0.6.3", default-features = false }
log = { version = "0.4.27", features = ["std"] }
serde = { version = "1.0.219", features = ["derive"] }
rand_core = "0.9.3"
rand = { version = "0.9", default-features = false }
rand_distr = { version = "0.5.1" }
wyrand = { version = "0.3.2" }
hashbrown = { version = "0.15.2", default-features = false, features = [
    "equivalent",
    "inline-more",
] }
rapidhash = { version = "4.1.0", default-features = false }
fastrace = { version = "0.7.9" }
fastrace-futures = { version = "0.7.9" }
logforth = { version = "0.26", features = [
    "append-fastrace",
    "append-opentelemetry",
    "diagnostic-fastrace",
] }
unicode-segmentation = "1.12.0"
itertools = "0.14.0"
parking_lot = "0.12.3"
indexmap = "2.9.0"
tokio = { version = "1.44.2", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "time",
    "parking_lot",
    "net",
    "signal",
] }
tokio-stream = { version = "0.1.17" }
futures-lite = "2.6.0"
pin-project-lite = "0.2.16"
scc = "2.3.3"
tower = { version = "0.5.2" }
tower-http = { version = "0.6.2", features = [
    "compression-br",
    "compression-gzip",
    "compression-zstd",
    "normalize-path",
    "request-id",
    "add-extension",
    "util",
] }

[package]
name = "nailpit"
edition.workspace = true
repository.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "nailpit"

[features]
default = ["mimalloc"]
tracing = ["fastrace/enable"]
mimalloc = ["dep:mimalloc-safe"]

[dependencies]
nailkov = { path = "crates/nailkov" }
nailrng = { path = "crates/nailrng" }
nailconfig = { path = "crates/nailconfig" }
nailstream = { path = "crates/nailstream" }
nailgen = { path = "crates/nailgen" }
nailrater = { path = "crates/nailrater" }
nailtrace = { path = "crates/nailtrace" }
nailstate = { path = "crates/nailstate" }
nailip = { path = "crates/nailip" }
nailotel = { path = "crates/nailotel" }
nailroutes = { path = "crates/nailroutes" }
nailspicy = { path = "crates/nailspicy" }
axum.workspace = true
tokio.workspace = true
color-eyre.workspace = true
log.workspace = true
fastrace.workspace = true
logforth.workspace = true
futures-concurrency = "7.6.3"
glob = "0.3.2"
mimalloc-safe = { version = "0.1.50", optional = true }
socket2 = "0.6.0"

[profile.release]
codegen-units = 1
lto = "fat"
debug = true
panic = "abort"
