[workspace]
resolver = "3"
members = ["nailconfig", "nailfv", "nailgen", "nailkov", "nailrater", "nailrng", "nailstream", "nailtrace"]

[workspace.package]
authors = ["Gonçalo Rica Pais da Silva <bluefinger@gmail.com>"]
edition = "2024"
repository = "https://github.com/Bluefinger/nailpit"
version = "0.1.0"
license = "AGPL-3.0-only"
rust-version = "1.86.0"

[workspace.lints.clippy]
undocumented_unsafe_blocks = "warn"

[workspace.dependencies]
axum = { version = "0.8.1", default-features = false, features = ["tokio", "http1", "http2"] }
axum-core = { version = "0.5.0", default-features = false }
bytes = "1.10.1"
hyper = { version = "1.6.0", default-features = false, features = ["server"] }
color-eyre = { version = "0.6.3", default-features = false }
log = { version = "0.4.27", features = ["std"] }
serde = { version = "1.0.219", features = ["derive"] }
rand_core = "0.9.3"
rand = { version = "0.9", default-features = false }
rand_distr = { version = "0.5.1" }
wyrand = { version = "0.3.2", features = ["wyhash", "fully_randomised_wyhash"] }
hashbrown = { version = "0.15.2", default-features = false, features = [
    "equivalent",
    "inline-more",
] }
fastrace = { version = "0.7.9" }
fastrace-futures = { version = "0.7.9" }
unicode-segmentation = "1.12.0"
itertools = "0.14.0"
parking_lot = "0.12.3"
indexmap = "2.9.0"
tokio = { version = "1.44.2", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "time",
    "parking_lot",
    "net",
    "signal",
] }
tokio-stream = { version = "0.1.17" }
futures-lite = "2.6.0"
pin-project-lite = "0.2.16"
scc = "2.3.3"
tower = { version = "0.5.2" }
tower-http = { version = "0.6.2", features = [
    "compression-br",
    "compression-gzip",
    "compression-zstd",
    "normalize-path",
    "request-id",
    "util"
] }

[package]
name = "nailpit"
edition.workspace = true
repository.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "nailpit"

[features]
default = ["mimalloc"]
tracing = ["fastrace/enable"]
mimalloc = ["dep:mimalloc-safe"]

[dependencies]
nailkov = { path = "nailkov" }
nailrng = { path = "nailrng" }
nailconfig = { path = "nailconfig" }
nailstream = { path = "nailstream" }
nailgen = { path = "nailgen" }
nailrater = { path = "nailrater" }
nailtrace = { path = "nailtrace" }
axum.workspace = true
axum-core.workspace = true
hyper.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tower-service = { version = "0.3.3", default-features = false }
color-eyre.workspace = true
wyrand.workspace = true
rand_core.workspace = true
rand.workspace = true
log.workspace = true
fastrace.workspace = true
fastrace-futures.workspace = true
logforth = { version = "0.25", features = ["fastrace", "opentelemetry"] }
tower.workspace = true
futures-concurrency = "7.6.3"
bytes.workspace = true
scc.workspace = true
parking_lot.workspace = true
tower-http.workspace = true
serde.workspace = true
glob = "0.3.2"
futures-lite.workspace = true
mimalloc-safe = { version = "0.1.50", optional = true }
pin-project-lite.workspace = true
fastrace-opentelemetry = "0.10.0"
opentelemetry = { version = "0.29.1", default-features = false, features = ["trace", "logs"] }
opentelemetry-otlp = { version = "0.29.0", default-features = false, features = ["trace", "logs", "grpc-tonic", "zstd-tonic"] }
opentelemetry_sdk = { version = "0.29.0", default-features = false, features = ["trace", "logs"] }

[profile.release]
codegen-units = 1
lto = "fat"
strip = true
panic = "abort"
