[package]
name = "nailstream"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
axum.workspace = true
hyper.workspace = true
futures-lite.workspace = true
tracing.workspace = true
