[package]
name = "nailconfig"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
serde.workspace = true
nailbox = { path = "../nailbox" }
config = { version = "0.15.11", default-features = false, features = ["toml"] }
color-eyre.workspace = true
