[package]
name = "nailotel"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
tracing = ["fastrace/enable"]

[dependencies]
nailconfig = { path = "../nailconfig" }
log = { workspace = true, features = ["kv"] }
fastrace.workspace = true
logforth = { workspace = true, features = ["layout-text", "layout-json", "bridge-log"] }
fastrace-opentelemetry = "0.14.0"
color-eyre.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true

[lints]
workspace = true
