[package]
name = "nailotel"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nailconfig = { path = "../nailconfig" }
fastrace.workspace = true
logforth.workspace = true
fastrace-opentelemetry = "0.11.0"
opentelemetry = { version = "0.30.0", default-features = false, features = ["trace", "logs"] }
opentelemetry-otlp = { version = "0.30.0", default-features = false, features = ["trace", "logs", "grpc-tonic", "zstd-tonic"] }
opentelemetry_sdk = { version = "0.30.0", default-features = false, features = ["trace", "logs"] }

[lints]
workspace = true
