[package]
name = "nailotel"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[features]

[dependencies]
nailconfig = { path = "../nailconfig" }
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-opentelemetry = { version = "0.32" }
color-eyre.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-semantic-conventions.workspace = true
opentelemetry-appender-tracing = "0.31"

[lints]
workspace = true
