[package]
name = "nailspicy"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nailconfig = { path = "../nailconfig" }
nailbox = { path = "../nailbox" }
hyper.workspace = true
rapidhash.workspace = true
hashbrown.workspace = true
tracing.workspace = true

[lints]
workspace = true
