[package]
name = "nailstate"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nailrng = { path = "../nailrng" }
nailconfig = { path = "../nailconfig" }
nailgen = { path = "../nailgen" }
nailkov = { path = "../nailkov" }
axum.workspace = true
rand.workspace = true

[lints]
workspace = true
