[package]
name = "nailgen"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
detailed_traces = []

[dependencies]
nailkov = { path = "../nailkov" }
nailconfig = { path = "../nailconfig" }
nailrng = { path = "../nailrng" }
nailbox = { path = "../nailbox" }
color-eyre.workspace = true
pin-project-lite.workspace = true
futures-lite.workspace = true
axum.workspace = true
rand.workspace = true
bytes.workspace = true
tracing.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
winnow.workspace = true
