[package]
name = "nailkov"
edition.workspace = true
repository.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
nailrng = { path = "../nailrng" }
rapidhash = { workspace = true, features = ["rand", "unsafe"] }
rustc-hash = { version = "2.1.1", default-features = false }
hashbrown.workspace = true
rand.workspace = true
rand_distr.workspace = true
itertools.workspace = true
unicode-segmentation.workspace = true
log.workspace = true
indexmap.workspace = true
