[package]
name = "nailroutes"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nailtrace = { path = "../nailtrace" }
nailgen = { path = "../nailgen" }
nailip = { path = "../nailip" }
nailrater = { path = "../nailrater" }
nailstate = { path = "../nailstate" }
nailspicy = { path = "../nailspicy" }
nailrng = { path = "../nailrng" }
tracing.workspace = true
tracing-futures.workspace = true
actix-web.workspace = true

[lints]
workspace = true
