[package]
name = "nailroutes"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nailtrace = { path = "../nailtrace" }
nailip = { path = "../nailip" }
nailrater = { path = "../nailrater" }
nailstate = { path = "../nailstate" }
nailstream = { path = "../nailstream" }
nailspicy = { path = "../nailspicy" }
axum = { workspace = true, features = ["original-uri"] }
hyper.workspace = true
fastrace.workspace = true
fastrace-futures.workspace = true
tower.workspace = true
tower-http.workspace = true

[lints]
workspace = true
