[package]
name = "nailtrace"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nailip = { path = "../nailip" }
nailnet = { path = "../nailnet" }
axum = { workspace = true, features = ["matched-path"] }
fastrace.workspace = true
hyper.workspace = true
tower-http.workspace = true
pin-project-lite.workspace = true
opentelemetry-semantic-conventions = "0.30"
uuid = { version = "1.17.0", features = ["v4", "fast-rng"] }

[lints]
workspace = true
