[package]
name = "nailtrace"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
emit_event_on_error = []

[dependencies]
nailip = { path = "../nailip" }
nailstate = { path = "../nailstate" }
nailrequest = { path = "../nailrequest" }
actix-web.workspace = true
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-futures.workspace = true
pin-project-lite.workspace = true
opentelemetry.workspace = true
opentelemetry-http.workspace = true
opentelemetry-semantic-conventions.workspace = true

[lints]
workspace = true
