[package]
name = "nailtrace"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nailip = { path = "../nailip" }
axum = { workspace = true, features = ["matched-path"] }
tracing.workspace = true
tracing-opentelemetry.workspace = true
hyper.workspace = true
tower-http.workspace = true
pin-project-lite.workspace = true
opentelemetry-semantic-conventions.workspace = true
tracing-opentelemetry-instrumentation-sdk = { version = "0.32", features = ["http"]}
uuid = { version = "1.17.0", features = ["v4", "fast-rng"] }

[lints]
workspace = true
