[package]
name = "nailkov"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, optional = true }
rand.workspace = true
rand_distr.workspace = true
wyrand.workspace = true
hashbrown.workspace = true
itertools.workspace = true
unicode-segmentation.workspace = true
log.workspace = true
indexmap.workspace = true

[features]
serde = ["dep:serde", "rand/serde"]
