[package]
name = "nailserve"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nailip = { path = "../nailip" }
axum.workspace = true
hyper.workspace = true
hyper-util = { version = "0.1", features = ["tokio", "server-auto", "server-graceful", "http1", "http2"] }
tower.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
color-eyre.workspace = true
futures-concurrency.workspace = true

[lints]
workspace = true
