[package]
name = "nailrater"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
detailed_traces = []

[dependencies]
nailfv = { path = "../nailfv" }
nailconfig = { path = "../nailconfig" }
nailspicy = { path = "../nailspicy" }
nailip = { path = "../nailip" }
nailbox = { path = "../nailbox" }
axum.workspace = true
futures-lite.workspace = true
hyper.workspace = true
pin-project-lite.workspace = true
parking_lot.workspace = true
tracing.workspace = true
tracing-futures.workspace = true
scc.workspace = true
tokio.workspace = true
rapidhash.workspace = true
tower.workspace = true

[lints]
workspace = true
