[server]
pit_routes = ["/private"]
socket_addr = "0.0.0.0:3000"
worker_threads = 1

[generator]
input_files = "input/*.txt"
warning_template = "templates/warning.html"
warning_message = "templates/message.txt"
generated_template = "templates/generated.html"
min_paragraph_size = 128
max_paragraph_size = 256
max_pit_links = 4
header_size = 32
payload_size = 100
timeout = 60
min_delay = 0
max_delay = 100
chunk_size = 4096

[rate_limiting]
type = "soft_limit"
soft_limit = 200
soft_delay = 600

[open_telemetry]
endpoint = "http://127.0.0.1:4317"
service_name = "nailpit"
logs = false
traces = false
