[package]
name = "nailrt"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nailconfig = { path = "../nailconfig" }
nailkov = { path = "../nailkov" }
nailgen = { path = "../nailgen" }
nailspicy = { path = "../nailspicy" }
nailstate = { path = "../nailstate" }
nailotel = { path = "../nailotel" }
color-eyre.workspace = true
core_affinity = "0.8.3"
futures-concurrency.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[lints]
workspace = true
