[package]
name = "nailrequest"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
actix-web.workspace = true
tracing.workspace = true
uuid = { version = "1.18", features = ["v7", "fast-rng"] }

[dev-dependencies]
actix-web = { workspace = true, features = ["macros"] }

[lints]
workspace = true
